  alter table Account 
       drop constraint FK1D0C220D7F5555FE;

    drop table Account if exists;

    drop table Equipment if exists;

    drop table Person if exists;

    create table Account (
        id integer generated by default as identity (start with 1),
        subscriber_id bigint,
        primary key (id)
    );

    create table Equipment (
        id bigint not null,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table Person (
        id bigint generated by default as identity (start with 1),
        city varchar(255),
        provinceOrState varchar(255),
        streetAddress varchar(255),
        firstName varchar(255),
        lastName varchar(255),
        middleName varchar(255),
        primary key (id)
    );

    alter table Account
        add constraint FK1D0C220D7F5555FE
        foreign key (subscriber_id)
        references Person;



insert into PUBLIC.PERSON (PERSON.CITY, PERSON.PROVINCEORSTATE, PERSON.STREETADDRESS, PERSON.FIRSTNAME, PERSON.LASTNAME, PERSON.MIDDLENAME)
values ('Toronto', 'Ontario', '1 Yonge', 'Samuel', 'Vimes', '');

insert into PUBLIC.PERSON (PERSON.CITY, PERSON.PROVINCEORSTATE, PERSON.STREETADDRESS, PERSON.FIRSTNAME, PERSON.LASTNAME, PERSON.MIDDLENAME)
values ('Toronto', 'Ontario', '1 Bloor', 'Havelock', 'Vettinari', '');

insert into PUBLIC.ACCOUNT(ACCOUNT.SUBSCRIBER_ID) VALUES (1);

insert into PUBLIC.ACCOUNT(ACCOUNT.SUBSCRIBER_ID) VALUES (2);